---

language: node_js

node_js:
  - 10.17.0

sudo: required

services:
  - docker

os:
- linux

dist: bionic

before_install:
  - sudo add-apt-repository -y ppa:elementary-os/os-patches
  - sudo apt-get update
  - sudo apt-get -y install meson libtag1-dev libtag1v5-vanilla

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-5-dev

install: true
script:
  - meson build --prefix=/usr
  - cd build
  - sudo ninja install
